version: '2'

services:
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_DATABASE=your-database
      - MYSQL_USER=your-user
      - MYSQL_PASSWORD=your-password
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - django_admin_static:/django_admin_static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    working_dir: /code/Firefly
    volumes:
      - .:/code
      - django_admin_static:/usr/local/lib/python3.6/site-packages/django/contrib/admin/static
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  django_admin_static:
